### PR TITLE
Try factor armor per 3d_armor

### PR DESCRIPTION
**Pull request by everamzah**
Not sure how you feel about this, but I have been using 3d_armor (with enchantment table for extra protection).  This might allow to use both, currently they conflict.  I've grown somewhat attached to 3d_armor -- thoughts?

### CODE REVIEW

**Comment by duane-r** [comment]
That's fine with me, but I don't plan to balance the monsters around using both together. They might make the game a little trivial. Even the bronze elixir makes the goblins a bit boring.

You might also want to change the abm that restores normal armor, unless 3d armor changes it periodically.

https://github.com/duane-r/fun_caves/commit/d8dbf6a4af3ddfb9005ce44f2fc5bcfe01fdedaf

**Comment by everamzah** [comment]
I'm running a modified version of 3d_armor with fun_caves @ https://github.com/everamzah/minetest-3d_armor/tree/fcs

I'm seriously considering dropping 3d_armor, though.  I don't want to, and I believe it's possible to account for fun_caves elixir in 3d_armor, so I will try.  (https://github.com/everamzah/fun_caves/tree/armor_restore)

As I learn more, I can't help but wonder whether the elixir should define its own armor group (say, {elixir=n}), coupled with minetest.register_on_hpchange() to determine how lessened the damage should be.

However, simply not playing with any armor mod might be the best course, of course!

**Comment by duane-r** [comment]
If I were you, I'd keep the armor mods and just comment out the armor section of the elixirs. Using either alone ought to be fine. I just like the idea of a potion better than building armor. You probably shouldn't remove the whole elixirs file, because I want to put other items in there that have nothing to do with armor.

**Comment by everamzah** [comment]
I shouldn't have multiplied by the factor on_use().  Now, I imagine, a player can use a low-level elixir repeatedly to reach a low fleshy rating.

I'll adapt the armor to the elixirs, or I'll remove the armor.  I like fun_caves most!

**Comment by duane-r** [comment]
No problem. I just added a check for existing elixir armor.

**Pull request closed without merging**
